# This is a basic workflow to help you get started with Actions

name: Compile & Publish 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/extra

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get eisvogel.tex
        run: wget https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex

      - name: Compile Markdown to PDF
        run: find . -type f -iname "*.md" -exec pandoc --template=eisvogel.tex -o output.pdf -s {} +
        
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          file: output.pdf
          asset_name: oi-si-statnice.pdf
          release_name: Release
          overwrite: true
          
      - name: Create output folder
        run: mkdir _site
          
      - name: Compile Markdown to HTML
        run: find . -type f -iname "*.md" -exec pandoc --template=eisvogel.tex -o _site/output.html --metadata title="OI - SI - Státnicové okruhy" -s {} +
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_site/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
