# This is a basic workflow to help you get started with Actions

name: Compile & Publish 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Pandoc and LaTeX
        run: sudo apt-get update & sudo apt-get install -y pandoc texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

      - name: Compile Markdown to PDF
        run: find . -type f -iname "*.md" -exec pandoc {} -s --pdf-engine=xelatex -V geometry:margin=1in --template=Eisvogel.latex -o output.pdf \;
        
      - name: Upload PDF
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Compiled-PDF
          path: output.pdf
